dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
    }
}
rootProject.name = "reschool"
include ':app'
include ':ORLib'
project(':ORLib').projectDir = file('../../console-android/ORLib')
