dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
    maven {
      url = "https://central.sonatype.com/repository/maven-snapshots"
    }
    maven {
      url = "https://jitpack.io"
    }
  }
}
rootProject.name = "reschool"
include ':app'
