org.gradle.parallel=true

projectName = ourgrid
version = 1.1-SNAPSHOT

openremoteVersion = 1.26.1
openremoteExtensionsVersion = 0.7.1

jacksonVersion = 2.21.4
typescriptGeneratorVersion = 4.1.1

# Versions for project-specific dependencies
rabbitMqAmqpClientVersion = 5.26.0

junitVersion = 6.0.3
junitPlatformVersion = 1.14.1
mockitoVersion = 5.23.0
testLoggerVersion = 4.0.0
