apply plugin: "java-library"

dependencies {
    api project(":agent")
    api project(":model")
    api "io.openremote:openremote-container:$openremoteVersion"
    api "io.openremote:openremote-manager:$openremoteVersion"
    api "io.openremote.extension:openremote-ems-extension:$openremoteExtensionsVersion"
}

tasks.register('installDist') {
    dependsOn jar
}
