workspace 'OurGrid'
platform :ios, '14.0'

use_frameworks!

pod 'ORLib', '~> 0.3'

pod 'Popover'
pod 'MaterialComponents/TextFields'
pod 'MaterialComponents/Buttons'

target 'OurGrid' do
  project 'OurGrid'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'IQKeyboardManagerSwift'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
                  config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
               end
          end
   end
end
