# OpenRemote v3
#
# Profile for doing keycloak custom theme development
#
# Please see profile/deploy.yml for configuration details for each service.
#
version: '2.4'

services:

  keycloak:
    extends:
      file: ../../openremote/profile/deploy.yml
      service: keycloak
    volumes:
      # Map custom themes
      - ../deployment:/deployment
    # Access directly if needed on localhost
    ports:
      - "8081:8080"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT:-8080}
      # Prevent theme caching during dev
      KEYCLOAK_START_OPTS: --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false

  postgresql:
    extends:
      file: ../../openremote/profile/deploy.yml
      service: postgresql
    #image: openremote/postgresql@sha256:b0a39e4baa12b2d02a9e694c1104edc8c0b8029f5d066cde4d373dfbf500fe22
    image: openremote/postgresql:${POSTGRESQL_VERSION:-latest-slim}
    volumes:
      - ../openremote/tmp:/storage
    # Access directly if needed on localhost
    ports:
      - "5432:5432"
