apply plugin: "java-library"

dependencies {
    api project(":model")
    api "io.openremote:openremote-agent:$openremoteVersion"

    // https://mvnrepository.com/artifact/com.rabbitmq/amqp-client
    implementation "com.rabbitmq:amqp-client:$rabbitMqAmqpClientVersion"
}

tasks.register('installDist') {
    dependsOn jar
}
