import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent

plugins {
  id 'java-library'
  alias libs.plugins.testLogger
}

configurations {
  mockitoAgent
}

dependencies {
  api project(":model")
  api libs.openremote.agent
  api libs.openremote.manager
  api libs.openremote.energy.extension

  implementation libs.rabbitmq.amqp.client
  implementation libs.jackson.datatype.jsr310

  testImplementation libs.junit.jupiter.api
  testImplementation libs.junit.jupiter.engine
  testImplementation libs.junit.platform.launcher
  testImplementation libs.mockito.core

  mockitoAgent(libs.mockito.core) {
    transitive = false
  }
}

tasks.register('installDist') {
  dependsOn jar
}

tasks.withType(Test).configureEach {
  environment("LOGGING_CONFIG_FILE", "test/src/logging-test.properties")
  addTestListener(new TestSummaryListener())
}

test {
  workingDir = findProject(":openremote") != null ? project(":openremote").projectDir : rootProject.projectDir
  jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
  useJUnitPlatform()
  testLogging {
    // set options for log level LIFECYCLE
    events = [TestLogEvent.FAILED, TestLogEvent.PASSED, TestLogEvent.SKIPPED]
    exceptionFormat = TestExceptionFormat.FULL
    showExceptions = true
    showCauses = true
    showStackTraces = true

    // set options for log level DEBUG and INFO
    debug {
      events = [
        TestLogEvent.STARTED,
        TestLogEvent.FAILED,
        TestLogEvent.PASSED,
        TestLogEvent.SKIPPED,
        TestLogEvent.STANDARD_ERROR
      ]
      exceptionFormat = TestExceptionFormat.FULL
    }
    info.events = debug.events
    info.exceptionFormat = debug.exceptionFormat
  }
}
