apply plugin: "java-library"

dependencies {
    api project(":model")
    api "io.openremote:openremote-agent:$openremoteVersion"

    // https://mvnrepository.com/artifact/com.rabbitmq/amqp-client
    implementation group: 'com.rabbitmq', name: 'amqp-client', version: '5.16.0'
}

tasks.register('installDist') {
    dependsOn jar
}
